### PR TITLE
toString supports null keys or values 

### PR DESCRIPTION
**Pull request by CaselIT**
Fixed exception 
TypeError: Cannot read property `toString` of null 
when calling toString and a key or a value is null.

### CODE REVIEW

**Comment by basarat** [comment]
A `null` key feels very bad :-/ Don't want this to silently go unnoticed. Is this null coming for our code or your team's code :rose:? 

I feel like its similar to someone doing `foo.bar()` when `foo` is `null`. Shouldn't go unnoticed :rose:

**Comment by CaselIT** [comment]
I agree that a `null` key or value is not the best thing, but it's not ideal to allow the dictionary to accept them and then throw an exception on the `toString` method.
The `null` is a value I added, it's not coming from the library code

**Comment by CaselIT** [comment]
@basarat I modified the code so that it does not calls `toString` but uses the implicit call done by javascript when representing an object as a string. This way it behaves correctly in either case.
What do you think?

**Comment by basarat** [comment]
Nice idea :+1: :rose:

**Pull request merged**
