### PR TITLE
Split modules

### PR DESCRIPTION
**Pull request by phiresky**
Split classes into single files. 

This means they can be used on their own via

`var PriorityQueue = require('./.../PriorityQueue');`

or in Typescript/ES6 `import PriorityQueue from './.../PriorityQueue';`

`collections.js` still contains all classes in the `collections` object, packed using browserify (see `build.bat`)

### CODE REVIEW

**Comment by basarat** [comment]
Looks great!. Ready to merge?

**Comment by phiresky** [comment]
I'm not sure if this currently works for all module systems. 
Also the `collections.d.ts` file is currently out of date it should be recreated (haven't looked into that)

**Comment by phiresky** [comment]
Nevermind, the collections.d.ts file is correct, but needs the other .d.ts files in `src/`. Not sure if committing all those would be the best idea. I think seperation of the generated files from the source files would be good but I'm not sure how best to do that.

**Comment by phiresky** [comment]
@basarat I added the generated .d.ts files. Not optimal, but it can be merged now.

**Comment by basarat** [comment]
Cheers :rose:

**Pull request merged**
