### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by episage**
makes it usable via npm 

`import * as collections from "typescript-collections";`

### CODE REVIEW

**Comment by basarat** [comment]
@episage I've added you as a collaborator. Merge away :rose:

**Comment by basarat** [comment]
Tell me your npm name and I'll add you there too :rose:

**Comment by episage** [comment]
@basarat Thanks for the rose. It's episage as well

**Comment by basarat** [comment]
@episage _done_ :rose: https://www.npmjs.com/package/typescript-collections 

image

# Some tips:

```
npm version [major|minor|patch]
```

Can prepare a release for you (update your package.json + add a git tag).

 Just follow with
-  `git push --follow-tags` : to push the packa.json change + git tag to github 
- `npm publish`: to push to npm

**Comment by nhhockeyplayer** [comment]
I am not getting latest when I clone.

Can this be completed? Thanks

**Comment by nhhockeyplayer** [comment]
episage, are you going to close this and publish?

I dont want to muck with it. I would prefer to take whats published.

The current release is not modulable

advise please... its been a few days since my last ple for assistance

**Comment by episage** [comment]
I will do it in the evening. Need to double check its valid.

Best

**Pull request merged**
