### PR TITLE
toJSON for dictionary only (yet)

### LINKED ISSUE #91: JSON Serializing Issue
Dictionary.toString() gives a lot of unwanted stuff like this:
```json
{
     “table”: {
       “$$o0": {
         “key”: 0,
         “value”: {
           “players”: {
             “table”: {},
             “nElements”: 0
           },
           “id”: 0
         }
       },
       “$$o1”: {
         “key”: 1,
         “value”: {
           “players”: {
             “table”: {
               “$$o895": {
                 “key”: 895,
                 “value”: {
                   “user”: {
                     “displayName”: “895”,
                     “id”: 895,
                     “socketId”: “x-5xlmLI52NNs8jCAAAA”,
                     “state”: 206,
                     “gameId”: 1
                   }
                 }
               },
               “$$o997”: {
                 “key”: 997,
                 “value”: {
                   “user”: {
                     “displayName”: “997",
                     “id”: 997,
                     “socketId”: “yYoKDq1rheXgWi72AAAB”,
                     “state”: 206,
                     “gameId”: 1
                   }
                 }
               }
             },
             “nElements”: 2
           },
           “id”: 1
         }
       }
     },
     “nElements”: 2
   }
}
```
While I am expecting something like this:
```json
{
    "key": "value"
}
```

### PR DESCRIPTION
**Pull request by Talha-T**
However if you like this, I can implement this for other types too. Also this fixes #91 .

### CODE REVIEW

**Comment by Talha-T** [comment]
I was expecting for someone to say, convert logical OR operator into bitwise OR operator; but nobody saw it I guess.

**Comment by episage** [comment]
Hey @Talha-T , can I ask you to implement simple test case for this as well?

**Comment by Talha-T** [comment]
Sure, here you go

**Comment by episage** [comment]
Im fixing some leftovers you left

image

**Comment by episage** [comment]
@Talha-T You did a huge mess in this PR. 
The actual change you made you removed in `https://github.com/basarat/typescript-collections/pull/92/commits/d1891d7e53e585fb0435b25450fac8891bbd8fca`
lol

**Comment by Talha-T** [comment]
This was my one of first times using Github so I'm not surprised so much lol

**Comment by episage** [comment]
No worries, I fixed it

**Pull request closed without merging**
